language: c

compiler: gcc
dist: bionic
install: make
os: linux
sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install -y "linux-headers-$(uname -r)"

script:
  - make license
  - make
  - make test
  - make clean
